cat <<EOF | kubectl apply -f -
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: katchblog-cert
  namespace: katchblogtest
spec:
  secretName: katchblog-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: katchblog.com
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  dnsNames:
  - katchblog.com
  - www.katchblog.com
  issuerRef:
    name:  "letsencrypt-staging"
    kind:  "ClusterIssuer"
    group: "cert-manager.io"
EOF