apiVersion: v1
kind: Service
metadata:
  name: informer
  namespace: inf
  labels:
    app: informer
spec:
  selector:
    app: informer
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: informer
  namespace: inf
  labels:
    app: informer
spec:
  selector:
    matchLabels:
      app: informer
  template:
    metadata:
      labels:
        app: informer
    spec:
      containers:
      - name: informer
        image: localhost:32000/informer
        ports:
        - containerPort: 8080
          name: informer